// Forward Collective — points earning engine.
//
// Pure functions only. No DB, no I/O. The server actions in src/lib/actions.ts
// call these, then persist the returned events with the service-role client.
// This keeps the math fully unit-testable (see points.test.ts).
//
// DOCUMENTED ASSUMPTIONS (resolved ambiguities from the spec):
// 1. Order-size multiplier uses >= ($100 order earns 1.25x, $200 earns 1.5x).
//    Tiers are mutually exclusive; the $200 tier supersedes the $100 tier.
// 2. The multiplier applies to BASE purchase points only, never to bonuses.
//    Base points = floor(orderAmount). The extra from the multiplier is logged
//    as a separate `order_size_bonus` event.
// 3. A "streak month" is a calendar month containing at least one purchase.
//    Buying twice in one month does not advance the streak; skipping a calendar
//    month resets it to 1.
// 4. One-time streak milestones (3/6/12) fire on the purchase that first reaches
//    that month count. After a 12-month streak, each purchase that extends the
//    streak into a NEW month earns +100 (it does not stack on the same month).
// 5. WELCOME_POINTS are credited at signup, not here.

import type { PointEventType } from "./types";

export const WELCOME_POINTS = 50;
export const EARLY_ACCESS_THRESHOLD = 6000;

export interface NewPointEvent {
  type: PointEventType;
  description: string;
  points: number;
}

export interface OrderInput {
  orderId: string;
  /** Order subtotal in dollars. */
  amount: number;
  /** Number of line items in the order. */
  itemCount: number;
  /** When the order was fulfilled. */
  purchaseDate: Date;
  /** User's purchase count BEFORE this order (0 for a first-ever order). */
  purchaseCountBefore: number;
  /** User's most recent prior purchase date, or null if this is their first. */
  lastPurchaseDate: Date | null;
  /** User's streak (in months) BEFORE this order. */
  currentStreakMonths: number;
}

export interface OrderResult {
  events: NewPointEvent[];
  totalEarned: number;
  newStreakMonths: number;
}

/** Difference in whole calendar months between two dates (b assumed >= a). */
export function calendarMonthDiff(a: Date, b: Date): number {
  return (b.getFullYear() - a.getFullYear()) * 12 + (b.getMonth() - a.getMonth());
}

/** Whole days between two dates. */
export function daysBetween(a: Date, b: Date): number {
  const MS = 24 * 60 * 60 * 1000;
  return Math.floor((b.getTime() - a.getTime()) / MS);
}

/** Compute the new streak given the prior streak and the purchase dates. */
export function computeStreak(
  prevStreak: number,
  lastPurchaseDate: Date | null,
  purchaseDate: Date
): number {
  if (!lastPurchaseDate) return 1;
  const diff = calendarMonthDiff(lastPurchaseDate, purchaseDate);
  if (diff <= 0) return Math.max(prevStreak, 1); // same month — no change
  if (diff === 1) return prevStreak + 1; // consecutive month
  return 1; // gap — reset
}

/** Order-size multiplier on base points. */
export function orderMultiplier(amount: number): number {
  if (amount >= 200) return 1.5;
  if (amount >= 100) return 1.25;
  return 1;
}

/**
 * Calculate every point event generated by a single fulfilled order.
 */
export function calcOrderPoints(input: OrderInput): OrderResult {
  const events: NewPointEvent[] = [];
  const {
    amount,
    itemCount,
    purchaseDate,
    purchaseCountBefore,
    lastPurchaseDate,
    currentStreakMonths,
  } = input;

  // --- Base purchase points: 1 per $1 ---
  const base = Math.floor(amount);
  if (base > 0) {
    events.push({
      type: "purchase_base",
      description: `Purchase — $${amount.toFixed(2)}`,
      points: base,
    });
  }

  // --- Order-size multiplier (logged as the extra over base) ---
  const mult = orderMultiplier(amount);
  if (mult > 1 && base > 0) {
    const extra = Math.round(base * (mult - 1));
    events.push({
      type: "order_size_bonus",
      description: `Order over $${amount >= 200 ? 200 : 100} — ${mult}x bonus`,
      points: extra,
    });
  }

  // --- Quantity bonus: 3+ items ---
  if (itemCount >= 3) {
    events.push({
      type: "quantity_bonus",
      description: "3+ items in one order",
      points: 50,
    });
  }

  // --- Recurring-purchase bonuses ---
  // 2nd purchase within 60 days of the first.
  if (
    purchaseCountBefore === 1 &&
    lastPurchaseDate &&
    daysBetween(lastPurchaseDate, purchaseDate) <= 60
  ) {
    events.push({
      type: "recurring_bonus",
      description: "2nd purchase within 60 days",
      points: 75,
    });
  }
  // 3rd purchase ever.
  if (purchaseCountBefore === 2) {
    events.push({
      type: "recurring_bonus",
      description: "3rd purchase",
      points: 50,
    });
  }

  // --- Streak bonuses ---
  const newStreak = computeStreak(
    currentStreakMonths,
    lastPurchaseDate,
    purchaseDate
  );
  const advanced = newStreak > currentStreakMonths; // moved into a new month
  if (advanced) {
    if (newStreak === 3) {
      events.push({ type: "streak_bonus", description: "3-month streak", points: 100 });
    } else if (newStreak === 6) {
      events.push({ type: "streak_bonus", description: "6-month streak", points: 200 });
    } else if (newStreak === 12) {
      events.push({ type: "streak_bonus", description: "12-month streak", points: 500 });
    } else if (newStreak > 12) {
      events.push({
        type: "streak_bonus",
        description: "Streak maintained past 12 months",
        points: 100,
      });
    }
  }

  const totalEarned = events.reduce((sum, e) => sum + e.points, 0);
  return { events, totalEarned, newStreakMonths: newStreak };
}

/** 1-year membership anniversary bonus. Fired by a scheduled job. */
export function anniversaryBonus(): NewPointEvent {
  return {
    type: "anniversary_bonus",
    description: "1-year membership anniversary",
    points: 150,
  };
}

/**
 * Referral bonus, applied when a referred user completes their first purchase.
 * Returns the event for each party.
 */
export function referralBonus(): {
  referrer: NewPointEvent;
  referred: NewPointEvent;
} {
  return {
    referrer: {
      type: "referral_bonus",
      description: "Referral — they made their first purchase",
      points: 200,
    },
    referred: {
      type: "referral_bonus",
      description: "Welcome bonus — referred by a member",
      points: 100,
    },
  };
}

/** Welcome bonus event, credited at signup. */
export function welcomeBonus(): NewPointEvent {
  return {
    type: "welcome_bonus",
    description: "Welcome to The Collective",
    points: WELCOME_POINTS,
  };
}

/** True once a user's lifetime total reaches the early-access threshold. */
export function crossesEarlyAccess(
  pointsBefore: number,
  pointsAfter: number
): boolean {
  return pointsBefore < EARLY_ACCESS_THRESHOLD && pointsAfter >= EARLY_ACCESS_THRESHOLD;
}
